# Generated by Django 4.2.2 on 2023-07-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baza_func',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=250)),
                ('specialist', models.CharField(max_length=250)),
                ('experience', models.TextField()),
                ('caste', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
                ('telegram_url', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Medic_programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_price', models.CharField(max_length=50)),
                ('first_service', models.CharField(max_length=50)),
                ('second_service', models.CharField(max_length=50)),
                ('third_service', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
